### ISSUE TITLE
Balance observations & feedback

### ISSUE THREAD

**Issue by grompe** [OreCruncher/ThermalRecycling#29]
Having played with this mod for a while, I have some observations to share.

These are valid for version 1.7.10-0.3.9.4ALPHA of ThermalRecycling.
- It's not obvious what the asterisk in the scrap value means.
  Perhaps it would be best to remove the tooltip for non-recycleable items instead.
- Too many of XP bottles are generated when recycling enchanted items.
  This makes fishing (and especially autofishing) too great of a farm.
  Even if one doesn't need XP levels, bottles still go at a good scrap value.
- Shift-clicking with the core in an attempt to upgrade Thermal Recycler makes it go into the recycling slot.
  I lost my first upgrade like that.
- Some of damaged items strangely have better scrap value than intact ones.
- Scrap repair values on default configuration are too high, and completely devalue using the original tool materials for repairs.
- In a recipe added to pulverizer, double of supposedly intended sawdust is generated from the diamond sword.
- If the intent is to make the Thermal Recycler feel like a Thermal Expansion machine, you might want to add augment slots for side configuration, auto-eject, etc.
- Chickens, when fed worms, lay too many eggs and too quickly.
- There's an exploit with an infinite cycle of Phyto-Gro (and similarly, Rich Phyto-Gro):
  `1 Pulverized Charcoal, 1 Niter, 1 Slag makes 32 Phyto-Gro`,
  and Thermal Recycler uses the
  `2 Sawdust, 1 Niter, 1 Slag -> 8 Phyro-Gro`
  recipe to reverse it, so it gives 8 Sawdust, 4 Niter and 4 Slag.
  8 Sawdust can be crafted, burned and pulverized again to 1 Pulverized Charcoal,
  making this the infinite source of Niter, Slag and Phyto-Gro, and all tiers of scrap.

**Comment by OreCruncher** [comment]
- I have been thinking about the asterisk.  The item still has scrap value as a component, but not cannot be directly inserted into a recycler.  Maybe I should add an additional line of text rather than have an asterisk.  I was trying to save some screen realestate, but in this case it may be better to be more explicit.
- XP bottles - any suggestion how much it should be reduced?  Fishing is a bit OP especially when automated fishing blocks are tossed in.  I am also contemplating changing the scrap value of XP bottles to poor which reduces their scrap potential.
- Shift-click.  I did the same thing. :)  It's been a nit on my list.  My plan is to make the logic sensative to the type of item stack and have cores go into the core slot on a shift+click instead of the item slot.
- Which damaged items?
- Scrap repair values.  Any suggestion as to what they should be?  Reduce by 50%?
- Diamond sword pulverizer.  Good catch.  Should be an easy fix.
- I thought about making the machine more TE like.  That logic is not provided in the CofHLib or Core libraries so I would have to write from scratch.  It's on my list of things to take a look at.
- Feeding worms to chickens.  Essentially the process converts worms to 0-3 eggs.  Is it the number of eggs that are given thats the issue, or the fact there isn't a time delay between feedings?
- An item with multiple recipes like that are a challenge.  The recipe logic will use the first one it encounters in the registry list.  I can hand make a recipe to handle, though I have an idea of how I can automate.

**Comment by grompe** [comment]
> Maybe I should add an additional line of text rather than have an asterisk.

Why? There's no direct use for recycling information if the item doesn't go recycle.

> XP bottles - any suggestion how much it should be reduced?

Right now I'd say 5x less. Reducing the scrap value of XP bottles is also a must.

> Which damaged items?

Vanilla fishing rods, bows, mods' tools, weapons and armor.

> Scrap repair values. Any suggestion as to what they should be? Reduce by 50%?

I'd say 5 times less. Or let it take in account how valuable the original material would be.

> Is it the number of eggs that are given thats the issue, or the fact there isn't a time delay between feedings?

Both. Could make it instead reduce the time the chicken will lay the next egg.

> An item with multiple recipes like that are a challenge.

Could make it so if an item has more than one recipe, refuse to break it to actual components.

Also I just noticed there's missing text for "achievement.lottowinner", speaking of which, sometimes diamonds and nether stars found in scrapboxes have nonzero damage value, making them unusable.

**Comment by OreCruncher** [comment]
The diamond an nether star thing is a bug.  Just looked at the code.

As for the asterisk the item does have scrap value, it's just that it cannot be directly inserted into the recycler.  If the item gets scrapped as a component the scrap value does have bearing on what type of scrap is produced.  For example, if an Iron Sword is scrapped the components are 2 Iron Ingots and 1 Stick.  The Iron Ingots are scrapped at "Standard" value, and the Stick is scrapped at "None" value.

Main concern I have with not somehow indicating this behavior is if someone tries to insert that Iron Ingot into a recycler and it doesn't go in what would they think?

**Comment by grompe** [comment]
So those items' scrap value is only relevant when looked at in the result section in the Scrap Assessor.

The solution is simple: let the item go in, but refuse to process with a sign and a description like ones you have now.

**Comment by OreCruncher** [comment]
As for the Phyto-gro situation, my thought was to analyze the original recipe output.  I think it could be reasonably assumed that if one recipe has stackSize of 8, and the other 32, the one with 32 is more expensive and should be the recipe.

This still isn't perfect, though.  For example, let's say that 32 Phyto recipe used a diamond instead of charcoal.  The player could make a bunch of Phyto using the cheap recipe, and then recycle it to get diamonds.  I would like to think that reasonable mod-authors would avoid things like this, but this is Minecraft. :)

This situation is one of the reasons I have supported mods.  For each mod that is supported I go through the items and recipes looking for stuff like this and do some handcoding around the problem.  Since it is a manual process it's not perfect.

**Comment by grompe** [comment]
Yep, that should be good enough. We cannot assume about all the mods, but the reason I mention this particular recipe is because it's in the requried one, Thermal Expansion. =)

**Comment by OreCruncher** [comment]
I will have to think on allowing the item going in.  Assuming I did this I could but the machine into a Jammed state.   Just that in this case it is jammed at the source and not at the output.

**Comment by grompe** [comment]
Right, allow this behavior for Scrap Assessor only?

**Comment by OreCruncher** [comment]
Not sure yet.  Definately for the Assessor - just wondering if it would be interesting to apply to the recycler as well.

**Comment by OreCruncher** [comment]
Just noticed something about the scrap repair values.  If I were to reduce the defaults to 20% of the current values those numbers would be where I started with the feature. :)  I bumped up because it seemed to be too low.  Still, I think it needs tweaking.

**Comment by OreCruncher** [comment]
The issues outlined in this entry have been split into separate issues to be tracked/handled.  As such I am going to close this entry.  If there is something missing go ahead and add as a separate entry.

Thanks for the input.  I appreciate it.

**Comment by grompe** [comment]
Great to see this mod improves! If it's more convenient for you, I will put separate points in separate issues from now on.

A little suggestion on handling, you may want to close issues with commit message by including text like
`closes #31` in it, it will also connect each issue to code that fixed it.
