### ISSUE TITLE
Strange interaction with Progressive Automation

### ISSUE THREAD

**Issue by Bomber57** [OreCruncher/ThermalRecycling#69]
So for whatever reason, vanilla iron tools, when recycled, produce Wither Iron from Progressive Automation (crafted with a Nether Star) rather than normal iron, which can obviously be a huge issue because you can basically turn iron into the much, much stronger wither iron for free. I believe you can do the same for diamond and get Wither Diamond. I tested with wood and stone tools and didn't get their respective tier of Wither material, but the point still stands.

This also only seems to happen with iron tools, for I also tested with heavy pressure plates and buckets and got normal iron ingots back.

**Comment by OreCruncher** [comment]
Can you use Wither Iron to make the mundane iron tools?

EDIT: Also what version of Thermal Recycling are you using?

**Comment by Bomber57** [comment]
The Wither Iron makes their respective Wither Iron tools, and in a smeltery will smelt down into Molten Wither Iron and do much the same.

I am using the most recent release version,  0.4.2.7 of Thermal Recycling.

**Comment by OreCruncher** [comment]
Actually the recipe makes an enchanted Iron Pick that has a special name.  Not sure what I can do at the moment, but I will think on it.

**Comment by OreCruncher** [comment]
Fix is to process recipes that have vanilla input and output prior to processing modded recipes.  Once the vanilla recipe is registered the modded recipe will not register because the vanilla one exists.  Note that Minetweaker scripts can modify this behavior by registering recipes FIRST.

The impact of this is that the pickaxe created using Wither Iron will be scrapped as if it were an enchanted Iron Pickaxe.

**Comment by OreCruncher** [comment]
In release v0.4.3.2ALPHA
