### ISSUE TITLE
[Enhancement] Use Forge Ore Dictionary to assign scrap values

### ISSUE THREAD

**Issue by zhs2** [OreCruncher/ThermalRecycling#75]
Right now I notice that a lot of like items get scrapped at a standard or superior value because they're hardcoded to be so in the mod (ex: Thermal Expansion ores, ingots, dusts) but anything alike receives a hard shaft with a scrap value of none (ex: ores, ingots, dusts from TCon, Foundry, FSP, Galacticraft, etc.) Ore Dictionary support for less annoyance and a reduced headache in cross-mod interaction pls?

**Comment by OreCruncher** [comment]
I understand what you are saying.  When I put in mod support I review the items, see how they are used in recipes, etc. to determine what value is placed on them.  I have come across items that have Forge dictionary equivalents, but in the context of the mod and recipes can be a bit OP if I allowed them to have equivalent scrap values.  Because of this and the nature of my mod I decided to be more conservative in assumptions.

I'm going to leave this open and mull it over.  I may be able to come up with a balanced way to handle.

**Comment by zhs2** [comment]
Base mine-able only resources (e.g. metals that turn into ingots into stuff) are a pretty good start at any rate, especially those found in large tech mods that a lot of them share (and generally have cloud-based generations of eight everywhere underground). I know the quality of most Minecraft items, especially from smaller mods, can vary wildly though :)

**Comment by OreCruncher** [comment]
Initial ALPHA release available: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v1.0.2.0ALPHA

**Comment by OreCruncher** [comment]
Released v1.0.2.2
