### ISSUE TITLE
Annoying Rubble Stacking

### ISSUE THREAD

**Issue by DrakoAlcarus** [OreCruncher/ThermalRecycling#87]
I keep getting this odd world gen...

<blockquote class="imgur-embed-pub" lang="en" data-id="MR35cGY"><a href="//imgur.com/MR35cGY">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

<blockquote class="imgur-embed-pub" lang="en" data-id="Vo9yNdi"><a href="//imgur.com/Vo9yNdi">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

<blockquote class="imgur-embed-pub" lang="en" data-id="jLJ12el"><a href="//imgur.com/jLJ12el">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

I happens when Biomes O' Plenty is installed.

Attempts per chunk to place rubble piles (higher more frequent discovery) [range: 0 ~ 2147483647, default: 80]
        I:Density=40

I have the chance reduced by 50%, but it still stacks. While it is minor, it drives me crazy. It also kinda throws off the balance.

**Comment by OreCruncher** [comment]
Does it _always_ stack?  I know that normally it is possible, but rare because of the distribution.

**Comment by DrakoAlcarus** [comment]
Not always, but it is noticeably frequent. The  screenshots I showed are all in the same ravine, with the mineshaft connected to it.

**Comment by DrakoAlcarus** [comment]
The world type I have is Biomes o' Plenty, but it may work with regular worlds with the mod kept installed.

**Comment by DrakoAlcarus** [comment]
Quick question... is rubble supposed to do this?

<blockquote class="imgur-embed-pub" lang="en" data-id="xr7Z7eN"><a href="//imgur.com/xr7Z7eN">Rubble in the Nether</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

I'm beginning to think that Boimes o' plenty may be registering the rubble as a plant, possibly? It seems to be biomes o' plenty that is generating the piles.

**Comment by OreCruncher** [comment]
Yeah.  I suspect that BoP is doing some squirrelly things with world gen.  More specifically, it is triggering and additional Flower gen process.  In Overworld this would cause piles to gen twice, one on top of the other due to world seed.  And it causes these piles to gen in the Nether when normal Vanilla doesn't do this.  To work around the Nether issue you can add the dimension to the rubble pile dimension blacklist.

EDIT: Clarification - Thermal Recycling places piles of rubble during the Flower generation phase of chunk gen.

**Comment by DrakoAlcarus** [comment]
I makes me feel good to know how to identify problems in codes and such.

If I make a mod called Thermal Reactors, is it possible you can add compatibility with the blocks in it, and the scrap boxes as modifiers in the Quantum Molecular Entangler (Basically a mass fabricator from IC2)

Unfortunately, I am an amateur modder, and have much to learn.

**Comment by OreCruncher** [comment]
It's possible.  What I would do on my end is add a support module for this new mod if it detects it as being present, such as what I do for Forestry, EnderIO, etc.  The Thermal Reactors mod could do something similar- if it detects Thermal Recycling as installed it could register the scrap items in it's internal recipes.

This being said, what you probably want to do is create an API so that a mod could register it's own items for use as modifiers in your QME.  As an example this is what AgriCraft has done for soils.  My mod registers Fertile Soil as farmland with AgriCraft so it knows it is OK to let the player place/use crop sticks on my soil block.

**Comment by DrakoAlcarus** [comment]
Ah, thanks! I will let you know when I make the mod.

Got any surefire ways to learn Java and modding quickly?

**Comment by OreCruncher** [comment]
Surefire and quickly? I'm afraid there isn't such a thing.  What I would do is start learning Java, and once you are familiar with it then try tackling a simple mod.  Reason is that if you try to learn modding with Forge while trying to learn Java you will quickly reach overload.  Also, if you know Java then you can look at what other folks have done with modding and learn by example.

**Comment by DrakoAlcarus** [comment]
Alright, thanks!

**Comment by OreCruncher** [comment]
Posted fix to CurseForge: http://minecraft.curseforge.com/projects/thermal-recycling/files/2269594.  I do think BoP is the root of these issues.  Need to do more investigation.
